import JSZip from 'jszip';
import type Konva from 'konva';
import type { Circuit, SimulationResult } from '../types';
import type { ElectroProject } from '../types/project';
import { bomToCsv } from './bomExport';
import { cableScheduleToCsv } from './cableScheduleExport';
import {
  buildCoordinationStudyData,
  buildCoordinationStudyPdf,
} from './coordinationStudyReport';
import { buildDrawingPdf, safeDrawingFileBase } from './drawingExport';
import { terminalScheduleToCsv } from './terminalScheduleExport';
import { wireScheduleToCsv } from './wireScheduleExport';

export type DocumentationPackManifestEntry = {
  fileName: string;
  description: string;
  included: boolean;
  skipReason?: string;
};

export function buildDocumentationPackManifest(
  circuit: Circuit,
  simulationResult: SimulationResult | null,
  baseFileName: string
): DocumentationPackManifestEntry[] {
  const base = safeDrawingFileBase(baseFileName);
  const entries: DocumentationPackManifestEntry[] = [
    {
      fileName: `${base}-drawing.pdf`,
      description: 'Schematic drawing with title block (multi-page when sheets configured)',
      included: true,
    },
    {
      fileName: `${base}-wire-schedule.csv`,
      description: 'Wire schedule — endpoints, colour, cross-section, tags',
      included: true,
    },
    {
      fileName: `${base}-bom.csv`,
      description: 'Bill of materials grouped by device type and rating',
      included: true,
    },
    {
      fileName: `${base}-terminal-schedule.csv`,
      description: 'Terminal connection schedule',
      included: true,
    },
    {
      fileName: `${base}-cable-schedule.csv`,
      description: 'Cable schedule with wizard sizing data per wire',
      included: true,
    },
  ];

  const coordination = buildCoordinationStudyData(circuit, simulationResult);
  if (coordination.devices.length > 0) {
    entries.push({
      fileName: `${base}-coordination-study.pdf`,
      description: 'Protection coordination study with device table and TCC curves',
      included: true,
    });
  } else {
    entries.push({
      fileName: `${base}-coordination-study.pdf`,
      description: 'Protection coordination study',
      included: false,
      skipReason: 'No protection devices (MCB, MCCB, fuse, ACB) in the active sheet',
    });
  }

  return entries;
}

export function formatDocumentationPackReadme(
  projectName: string,
  sheetName: string,
  exportedAt: string,
  manifest: DocumentationPackManifestEntry[]
): string {
  const lines = [
    'ElectroSim — Documentation pack',
    '================================',
    '',
    `Project: ${projectName}`,
    `Active sheet: ${sheetName}`,
    `Exported: ${exportedAt}`,
    '',
    'Contents',
    '--------',
  ];

  for (const entry of manifest) {
    if (entry.included) {
      lines.push(`  ${entry.fileName}`);
      lines.push(`    ${entry.description}`);
    } else {
      lines.push(`  (not included) ${entry.fileName}`);
      lines.push(`    ${entry.skipReason ?? entry.description}`);
    }
  }

  lines.push(
    '',
    'Generated by ElectroSim. Verify all schedules against the as-built drawing before issue.'
  );
  return lines.join('\r\n');
}

function triggerBlobDownload(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

export async function buildDocumentationPackZip(
  stage: Konva.Stage,
  circuit: Circuit,
  simulationResult: SimulationResult | null,
  project: Pick<ElectroProject, 'name' | 'titleBlock'>
): Promise<{ zip: JSZip; manifest: DocumentationPackManifestEntry[] }> {
  const base = safeDrawingFileBase(circuit.name || 'circuit');
  const manifest = buildDocumentationPackManifest(
    circuit,
    simulationResult,
    circuit.name || 'circuit'
  );
  const zip = new JSZip();

  const drawingDoc = await buildDrawingPdf(stage, circuit, project);
  zip.file(`${base}-drawing.pdf`, drawingDoc.output('arraybuffer'));

  zip.file(`${base}-wire-schedule.csv`, wireScheduleToCsv(circuit));
  zip.file(`${base}-bom.csv`, bomToCsv(circuit));
  zip.file(`${base}-terminal-schedule.csv`, terminalScheduleToCsv(circuit));
  zip.file(`${base}-cable-schedule.csv`, cableScheduleToCsv(circuit));

  const coordinationEntry = manifest.find(
    (e) => e.fileName === `${base}-coordination-study.pdf`
  );
  if (coordinationEntry?.included) {
    const coordDoc = buildCoordinationStudyPdf(circuit, simulationResult);
    zip.file(`${base}-coordination-study.pdf`, coordDoc.output('arraybuffer'));
  }

  const exportedAt = new Date().toISOString();
  zip.file(
    'README.txt',
    formatDocumentationPackReadme(
      project.name,
      circuit.name || 'Sheet',
      exportedAt,
      manifest
    )
  );

  return { zip, manifest };
}

export async function downloadDocumentationPack(
  stage: Konva.Stage,
  circuit: Circuit,
  simulationResult: SimulationResult | null,
  project: Pick<ElectroProject, 'name' | 'titleBlock'>
): Promise<void> {
  const base = safeDrawingFileBase(project.name || circuit.name || 'project');
  const { zip } = await buildDocumentationPackZip(
    stage,
    circuit,
    simulationResult,
    project
  );
  const blob = await zip.generateAsync({ type: 'blob' });
  triggerBlobDownload(blob, `${base}-documentation-pack.zip`);
}
