export {
  EXPORT_BODY_SM_LINE_MM as LEGEND_BODY_SM_LINE_MM,
  EXPORT_BODY_SM_PT as LEGEND_BODY_SM_PT,
  EXPORT_CAPTION_PT as LEGEND_CAPTION_PT,
  EXPORT_TITLE_SM_PT as LEGEND_TITLE_PT,
} from './exportTypography';
